sudo: true

services:
  - docker

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - env
  - docker pull ubuntu:artful
  - docker run -it -d --name nanolisp-dc ubuntu:artful
  - docker exec nanolisp-dc apt update
  - docker exec nanolisp-dc apt install -y cmake python3-pip
  - docker exec nanolisp-dc pip3 install --user cpp-coveralls
  - docker cp ${TRAVIS_BUILD_DIR} nanolisp-dc:/tmp/git

script:
  - docker exec nanolisp-dc /bin/bash -c "cd /tmp/git; mkdir build; cd build; cmake ..; make all; ./nanolisp-test"

after_success:
  - coveralls --root .. -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false