sudo: required

services:
  - docker

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - docker pull ubuntu/zesty
  - docker ps -a
  - docker run pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./nanolisp-test

after_success:
  - coveralls --root .. -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false