sudo: true

services:
  - docker

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - docker pull ubuntu:artful
  - docker start ubuntu:artful --name nanolisp-dc
  - docker exec nanolisp-dc apt update
  - docker exec nanolisp-dc apt install -y cmake
  - docker exec nanolisp-dc pip install --user cpp-coveralls'
  - docker ps -a

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./nanolisp-test

after_success:
  - coveralls --root .. -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false