sudo: required

services:
  - docker

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - docker pull ubuntu:artful
  - docker run --name nanolisp-dc ubuntu:artful bin/bash -c 'apt update && apt search cmake && apt install -y cmake'
  - docker run --name nanolisp-dc ubuntu:artful pip install --user cpp-coveralls
  - docker ps -a

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./nanolisp-test

after_success:
  - coveralls --root .. -E ".*googletest.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false